package arraystring.finddifferences;

import java.util.ArrayList;
import java.util.List;

public class FindTheDifference {

    /*
    You are given two strings s and t.
    String t is generated by random shuffling string s and then add one more letter at a random position.
    Return the letter that was added to t.
     */

//    String a1 = "abcd";
//    String a2 = "abcde";

    public static char findTheDifference(String s, String t) {

        List<Character> chars = new ArrayList<>();
        for (char x : t.toCharArray()) {
            chars.add(x);
        }
        for (int i = 0; i < s.length(); i++) {
            if (chars.contains(s.charAt(i))) {
                chars.remove(Character.valueOf(s.charAt(i)));
            }
        }
        return chars.get(0);
    }
}
